# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: DimonSmart.NugetMcpServer
PackageVersion: 1.0.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: NugetMcpServer.exe
  PortableCommandAlias: DimonSmart.NugetMcpServer
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/DimonSmart/NugetMcpServer/releases/download/v1.0.1/nuget-mcp-server-win-x64.zip
  InstallerSha256: 88B6DA61E435F9012FF86257A0532C33D571C03BD40095E488AB619CF02A8E2A
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-05-11
